version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Makefile dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # C++ dependencies
  - package-ecosystem: "cpp"
    directory: "/"
    schedule:
      interval: "weekly"

  # Shell dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
