name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:

  ci:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get install -y libcap-dev util-linux

      - name: Build
        run: |
          make CXX=g++-9 ECHO=echo OMEGAJAIL_RELEASE=${{ github.sha }} all
          cargo build --bins
          cargo build --tests

      - name: Test
        run: make test

      - name: Build rootfs
        run: make OMEGAJAIL_RELEASE=${{ github.sha }} rootfs

      - name: Smoketest
        run: |
          sudo mkdir -p -m 0775 /sys/fs/cgroup/memory/system.slice/omegaup-runner.service/omegajail
          sudo chown $(whoami) /sys/fs/cgroup/memory/system.slice/omegaup-runner.service/omegajail
          sudo chgrp $(whoami) /sys/fs/cgroup/memory/system.slice/omegaup-runner.service/omegajail
          taskset 0x1 ./smoketest/test --root=./rootfs --strace --cgroup-path=/system.slice/omegaup-runner.service/omegajail

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: smoketest/run/

  smoketest-docker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build container
        run: |
          make OMEGAJAIL_RELEASE=${{ github.sha }} .omegajail-builder-rootfs-runtime.stamp

      - name: Smoketest (Docker)
        run: |
          make OMEGAJAIL_RELEASE=${{ github.sha }} smoketest-docker

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-logs-docker
          path: smoketest/run/
