name: Release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@c170e78287f338a4af0dc49e033e50e5a072d82b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none
          INITIAL_VERSION: 1.0.0

      - name: Build omegajail-focal-distrib-x86_64.tar.xz
        if: ${{ steps.bump-version.outputs.part != '' }}
        run: make OMEGAJAIL_RELEASE=${{ steps.bump-version.outputs.tag }} omegajail-focal-distrib-x86_64.tar.xz

      - name: Build omegajail-focal-rootfs-x86_64.tar.xz
        if: ${{ steps.bump-version.outputs.part == 'major' || steps.bump-version.outputs.part == 'minor' }}
        run: make omegajail-focal-rootfs-x86_64.tar.xz

      - name: Create Release
        id: create-release
        if: ${{ steps.bump-version.outputs.part != '' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump-version.outputs.tag }}
          release_name: ${{ steps.bump-version.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload omegajail-focal-distrib-x86_64.tar.xz Release Asset
        if: ${{ steps.bump-version.outputs.part != '' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./omegajail-focal-distrib-x86_64.tar.xz
          asset_name: omegajail-focal-distrib-x86_64.tar.xz
          asset_content_type: application/octet-stream

      - name: Upload omegajail-focal-rootfs-x86_64.tar.xz Release Asset
        if: ${{ steps.bump-version.outputs.part == 'major' || steps.bump-version.outputs.part == 'minor' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./omegajail-focal-rootfs-x86_64.tar.xz
          asset_name: omegajail-focal-rootfs-x86_64.tar.xz
          asset_content_type: application/octet-stream
